# Generated by Django 4.2.7 on 2025-12-02 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o razón social del cliente', max_length=255)),
                ('email', models.EmailField(help_text='Email del cliente', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('empresa', 'Empresa'), ('particular', 'Particular'), ('distribuidor', 'Distribuidor')], default='particular', help_text='Tipo de cliente', max_length=20)),
                ('rut', models.CharField(blank=True, help_text='RUT del cliente', max_length=20, null=True, unique=True)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social para empresas', max_length=255)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Región', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal', max_length=20)),
                ('compra_minima', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra en CLP', max_digits=10)),
                ('es_activo', models.BooleanField(default=True, help_text='Cliente activo')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre el cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['email'], name='clientes_email_fb2cd6_idx'), models.Index(fields=['tipo_cliente'], name='clientes_tipo_cl_8125a0_idx')],
            },
        ),
    ]
