# Generated by Django 4.2.7 on 2025-12-02 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del remitente', max_length=255)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa (opcional)', max_length=255)),
                ('asunto', models.CharField(choices=[('consulta', 'Consulta General'), ('compra', 'Información de Compra'), ('distribuidor', 'Quiero ser Distribuidor'), ('reclamo', 'Reclamo'), ('otro', 'Otro')], default='consulta', help_text='Asunto del mensaje', max_length=20)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje')),
                ('leido', models.BooleanField(default=False, help_text='Mensaje leído por administrador')),
                ('respondido', models.BooleanField(default=False, help_text='Se ha enviado respuesta')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta enviada', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha en que se respondió', null=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'db_table': 'mensajes_contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
