# Generated by Django 4.2.7 on 2025-12-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('descripcion_corta', models.CharField(blank=True, help_text='Descripción breve para listados', max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable', unique=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en CLP', max_digits=10)),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento', max_digits=10, null=True)),
                ('imagen', models.ImageField(help_text='Imagen principal del producto', upload_to='productos/%Y/%m/')),
                ('imagenes_adicionales', models.CharField(blank=True, help_text='URLs de imágenes adicionales separadas por comas', max_length=1000)),
                ('cantidad_stock', models.IntegerField(default=0, help_text='Stock disponible')),
                ('especificaciones', models.TextField(blank=True, help_text='Especificaciones técnicas en formato JSON')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descatalogado', 'Descatalogado')], default='activo', help_text='Estado del producto', max_length=20)),
                ('es_destacado', models.BooleanField(default=False, help_text='Mostrar en sección destacados')),
                ('es_nuevo', models.BooleanField(default=False, help_text='Marcar como producto nuevo')),
                ('calificacion', models.FloatField(default=0, help_text='Calificación promedio (0-5)')),
                ('numero_resenas', models.IntegerField(default=0, help_text='Número de reseñas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['slug'], name='productos_slug_2a7ee0_idx'), models.Index(fields=['categoria'], name='productos_categor_169a62_idx'), models.Index(fields=['estado'], name='productos_estado_184900_idx')],
            },
        ),
    ]
