# Generated by Django 4.2.7 on 2025-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la categoría', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable', unique=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/')),
                ('es_activo', models.BooleanField(default=True, help_text='Si la categoría está visible en el sitio')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
